
services:
  web:
    build: 
      context: ${APP_DIR}
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    network_mode: host  # Use host network mode

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres_data:
